# Use root/example as user/password credentials
version: '3.3'

services:

  mongo:
    ports:
      - 27017:27017
    container_name: docker_mongodb
    image: mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - type: bind
        source: ./data
        target: /data/db