apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    type: frontendApp-rc
spec:
  template:
    metadata:
      name: siva-nginx-pod
      labels:
        app: my-app
        type: frontend
    spec:
      containers:
        - name: nginx-image
          image: nginx
  replicas: 3